# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Data')),
                ('reservation_time_start', models.TimeField(verbose_name='Rezerwacja od')),
                ('reservation_time_end', models.TimeField(verbose_name='Rezerwacja do')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa salki')),
                ('address', models.CharField(blank=True, max_length=254, verbose_name='Adres')),
                ('description', models.CharField(blank=True, max_length=254, verbose_name='Opis')),
                ('user', models.ManyToManyField(related_name='Użytkownik', through='dreservator_app.Reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Telefon')),
                ('is_instructor', models.BooleanField(default=False, verbose_name='Instruktor ?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='rooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreservator_app.Rooms'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
