# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreservator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_time',
            field=models.BooleanField(default=True, verbose_name='Nowa rejestracja'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='Instruktor'),
        ),
    ]
