# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreservator_app', '0004_auto_20180228_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Instruktor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Kursant'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='user',
            field=models.ManyToManyField(related_name='Użytkownik', through='dreservator_app.Reservations', to='dreservator_app.Rooms'),
        ),
    ]
