# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreservator_app', '0005_auto_20180228_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='user',
            field=models.ManyToManyField(related_name='Login', through='dreservator_app.Reservations', to='dreservator_app.Rooms'),
        ),
    ]
